In [1]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_log_error, mean_squared_error,mean_absolute_error



2021-11-30 12:56:21.842202: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-11-30 12:56:21.842245: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
data=pd.read_pickle("./dataframe/df_only_risky_events.pkl")
data.reset_index(inplace=True)
data.drop(['index'], inplace=True, axis=1)

In [3]:
train, test = train_test_split(data, test_size=0.30, random_state=42)
print("Train dataframe dimension {} x {}".format(train.shape[0],train.shape[1]))
print("Test dataframe dimension {} x {}".format(test.shape[0],test.shape[1]))
Y_train = train["COLLISSION_PROBABILITY"].values
X_train= train.drop(["COLLISSION_PROBABILITY"], axis=1).values
Y_test = test["COLLISSION_PROBABILITY"].values
X_test= test.drop(["COLLISSION_PROBABILITY"], axis=1).values

Train dataframe dimension 190 x 86
Test dataframe dimension 82 x 86


In [4]:
ncol=X_train.shape[1]

In [5]:
Y_train

array([-5.98842956, -4.67366414, -5.63059859, -5.52013689, -5.48958905,
       -4.50362395, -5.1258082 , -5.23336411, -5.32066297, -5.18615225,
       -5.14014148, -5.37273658, -5.13353543, -5.33282733, -4.76776648,
       -3.91399629, -4.50182734, -5.45642858, -5.54622314, -5.99139983,
       -5.02844585, -5.49295413, -5.91721463, -5.34275287, -5.55658054,
       -4.97469413, -5.97798426, -4.71264623, -5.72607322, -5.2772016 ,
       -5.68507994, -5.62874737, -5.54136215, -3.26672247, -4.74738966,
       -5.14660602, -5.85886391, -5.1820382 , -4.59670785, -5.8291518 ,
       -4.59739476, -5.51427857, -5.89109687, -5.81673016, -4.56415563,
       -3.34065436, -4.97839728, -4.72607322, -5.25391096, -4.40993877,
       -5.98213228, -5.01786451, -5.95703093, -4.69378949, -5.90343756,
       -5.6256183 , -5.96018945, -4.88472241, -5.52520118, -5.99396205,
       -5.83003183, -3.41839163, -5.80079352, -5.42596873, -5.04378353,
       -5.6181632 , -5.01999663, -4.80548566, -4.40760115, -5.69

In [6]:
# create model
model = Sequential()
model.add(Dense(int(ncol/2), input_dim=ncol, kernel_initializer='normal', activation='relu'))
model.add(Dense(int(ncol/2), activation= "relu"))
model.add(Dense(1, kernel_initializer='normal'))
# Compile model
model.compile(loss='mean_squared_error', optimizer='adam',metrics=["mean_squared_error"])


2021-11-30 12:56:25.315185: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-11-30 12:56:25.315237: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-11-30 12:56:25.315270: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (acer): /proc/driver/nvidia/version does not exist


In [7]:
model.fit(X_train, Y_train, epochs=3000,verbose=0)

In [8]:
pred_train= model.predict(X_train)
print(pred_train.shape)
print(np.sqrt(mean_squared_error(Y_train,pred_train)))


(190, 1)
107.84075734752547


In [9]:
# REGRESION MODEL METRICS
print("The r2 of prediction is:", r2_score(Y_train, pred_train))
print("The MSE of prediction is:", mean_squared_error(Y_train, pred_train, squared=True))
print("The RMSE of prediction is:", mean_squared_error(Y_train, pred_train, squared=False))
print("The MAE of prediction is:", mean_absolute_error(Y_train, pred_train))

The r2 of prediction is: -21824.8508107444
The MSE of prediction is: 11629.628945287868
The RMSE of prediction is: 107.84075734752547
The MAE of prediction is: 35.227406109738055


In [10]:
pred_train

array([[ 5.88099480e+00],
       [-4.54364014e+00],
       [ 1.86577392e+00],
       [ 1.02868481e+01],
       [ 8.20955038e-01],
       [-3.17457795e+00],
       [-4.76074409e+00],
       [ 1.07856960e+01],
       [ 4.56003380e+00],
       [-1.59820595e+01],
       [ 5.67013359e+00],
       [ 5.18607849e+02],
       [ 2.65222716e+00],
       [ 5.15710258e+00],
       [-1.83451721e+02],
       [-1.19688123e-01],
       [-3.14902711e+00],
       [-5.84305525e-01],
       [ 7.63445854e+00],
       [-2.47850895e+01],
       [ 3.80126305e+01],
       [-4.62843056e+01],
       [ 2.44272709e+01],
       [ 4.90588318e+02],
       [ 9.22706413e+00],
       [ 2.22493877e+01],
       [ 6.05578423e+00],
       [ 5.42034054e+00],
       [ 5.67413139e+00],
       [ 5.21541786e+00],
       [ 5.27044487e+00],
       [ 7.82514099e+02],
       [ 9.05499077e+00],
       [ 7.03937674e+00],
       [ 3.54314399e+00],
       [ 5.69864845e+00],
       [-4.14767647e+00],
       [-1.10128193e+01],
       [ 3.6

In [11]:
pred= model.predict(X_test)


In [12]:
pred

array([[ 6.5559368e+00],
       [ 5.4674206e+00],
       [ 2.5926939e+01],
       [ 3.8504007e+00],
       [-2.5524680e+02],
       [-2.0997332e+01],
       [ 5.1777972e+02],
       [ 9.7676754e+00],
       [ 7.2873516e+00],
       [ 1.4443541e+01],
       [-4.7983418e+00],
       [ 6.4270844e+01],
       [ 4.2069759e+01],
       [-6.0468403e+01],
       [-8.3864155e+00],
       [ 2.7115419e+00],
       [ 4.3885189e+01],
       [-4.0421936e-01],
       [ 1.2605102e+00],
       [-1.4710352e-01],
       [ 1.0987151e+00],
       [ 3.7052191e+02],
       [ 3.0639097e+01],
       [ 1.3975708e+00],
       [ 3.4134457e+01],
       [ 5.6605158e+00],
       [ 8.4063157e-02],
       [ 1.4115875e+01],
       [-4.6317326e+01],
       [ 4.1666946e+00],
       [ 2.5140182e+02],
       [-1.6832184e+02],
       [-5.8071003e+00],
       [ 5.2979916e+01],
       [ 4.9895515e+00],
       [ 3.6831071e+00],
       [ 5.8232662e+01],
       [ 3.5881307e+00],
       [ 5.8332394e+01],
       [ 5.8482479e+01],


In [13]:
# REGRESION MODEL METRICS
print("The r2 of prediction is:", r2_score(Y_test, pred))
print("The MSE of prediction is:", mean_squared_error(Y_test, pred, squared=True))
print("The RMSE of prediction is:", mean_squared_error(Y_test, pred, squared=False))
print("The MAE of prediction is:", mean_absolute_error(Y_test, pred))

The r2 of prediction is: -22811.698511195966
The MSE of prediction is: 12598.16035288435
The RMSE of prediction is: 112.24152686454488
The MAE of prediction is: 47.243598732977
